environment:
  API_KEY: ${API_KEY},
  DB_HOST: $(DB_HOST),
  DB_SUPERUSER_DB: $(DB_SUPERUSER_DB),
  DB_SUPERUSER: $(DB_SUPERUSER),
  DB_PASSWORD: $(DB_PASSWORD),
  DB_PORT: $(DB_PORT),

packages:
  - name: sample
    actions:
      - name: emails
        runtime: 'python:default'